"""puzzle table extra columns

Revision ID: 19d4eb6cb2fb
Revises: 
Create Date: 2025-05-01 23:23:30.072194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d4eb6cb2fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puzzle_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('par_time_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.Integer(), nullable=True))

    # fill existing data with placeholder values: name = Untitled, par time = 60 seconds, difficulty = 1
    op.execute("UPDATE puzzle SET puzzle_name = 'Untitled'")
    op.execute("UPDATE puzzle SET par_time_seconds = 60")
    op.execute("UPDATE puzzle SET difficulty = 1")

    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.alter_column('puzzle_name', nullable=False)
        batch_op.alter_column('par_time_seconds', nullable=False)
        batch_op.alter_column('difficulty', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.drop_column('difficulty')
        batch_op.drop_column('par_time_seconds')
        batch_op.drop_column('puzzle_name')

    # ### end Alembic commands ###
