"""Added SolvedPuzzle table and some constraints

Revision ID: 5829e7f561e9
Revises: ec6bff872e95
Create Date: 2025-05-05 09:50:06.955628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5829e7f561e9'
down_revision = 'ec6bff872e95'
branch_labels = None
depends_on = None

# Manual adjustments made to this file:
# Alembic didn't recognise the added check constraint on the puzzle table, so that was added manually to the upgrade and downgrade functions.
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solvedpuzzle',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('puzzle_id', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.CheckConstraint('accuracy > 0 AND accuracy <= 100', name='accuracy_checker'),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzle.puzzle_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'puzzle_id')
    )
    # Help from GenAI to write the following
    with op.batch_alter_table('puzzle') as batch_op:
        batch_op.create_check_constraint(
            'puzzle_size_check',
            'num_columns > 0 AND num_columns <= 20 AND num_rows > 0 AND num_rows <= 20'
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solvedpuzzle')
    # Help from GenAI to write the following
    with op.batch_alter_table('puzzle') as batch_op:
        batch_op.drop_constraint('puzzle_size_check', type_='check')    # ### end Alembic commands ###
