"""Added users and friends tables

Revision ID: ec6bff872e95
Revises: 19d4eb6cb2fb
Create Date: 2025-05-02 11:45:32.299460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec6bff872e95'
down_revision = '19d4eb6cb2fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('passwordHash', sa.String(length=256), nullable=False),
    sa.Column('userScore', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friends',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.alter_column('puzzle_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('par_time_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('difficulty',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_users_puzzles', 'users', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_puzzles', type_='foreignkey')
        batch_op.alter_column('difficulty',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('par_time_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('puzzle_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('creator_id')

    op.drop_table('friends')
    op.drop_table('users')
    # ### end Alembic commands ###
